apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
  namespace: fase4-tech-challenge
type: Opaque
stringData:
  SQL_SERVER_PASSWORD: "fiapUser1234"
  CONNECTION_STRING: "Server=sqlserver,1433; Database=Fase4TechChallenge; User Id=sa; Password=fiapUser1234; TrustServerCertificate=True"