version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-microservices
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-microservices
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-microservices
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=fiapUser1234
    ports:
      - "1434:1433"
    restart: unless-stopped
    volumes:
      - sqlserver-data:/var/opt/mssql
    # Healthcheck to ensure SQL Server is ready before other services start
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/1433"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-microservices
    ports:
    # Port for the AMQP protocol (for your application to connect)
      - "5672:5672"
    # Port for the Management UI (for you to see queues/messages)
      - "15672:15672"
    volumes:
    # This line ensures that all of RabbitMQ's data is saved to the host
      - rabbitmq-data:/var/lib/rabbitmq/
    # You can set a default user and password
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped
   
  persistence-api:
    image: vinicius1183/persistance-api:v1.0.1
    container_name: persistence-api-microservice
    restart: unless-stopped
    ports:
      # Map container ports to host ports (e.g., http: 7175->8080, https: 7176->8081)
      - "8080:8080"
    environment:
      # This passes the connection string from the .env file into the container
      # The key "ConnectionStrings__DefaultConnection" maps to the "DefaultConnection" section in appsettings.json
      - ConnectionStrings__DefaultConnection=${PERSISTENCE_API_CONNECTION_STRING}
      # ASP.NET Core environment and URLs configuration
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080;
    depends_on:
      # This ensures the API only starts after the database is fully healthy
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_started

volumes:
  grafana-data:
  sqlserver-data:
  rabbitmq-data: