global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'microservice-api'
    metrics_path: '/metrics'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:7068']
  
  - job_name: 'microservice-persistance-api'
    metrics_path: '/metrics'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:7175']