apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: fase4-tech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - containerPort: 1433
        env:
          - name: ACCEPT_EULA
            value: "Y"          
          - name: MSSQL_SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlserver-secret
                key: SQL_SERVER_PASSWORD
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
          - mountPath: /var/opt/mssql
            name: sqlserver-storage
      volumes:
        - name: sqlserver-storage
          persistentVolumeClaim:
            claimName: sqlserver-pvc