apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: fase4-tech-challenge
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/grafana

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: fase4-tech-challenge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi