apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlserver-pv
  namespace: fase4-tech-challenge
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/sqlserver

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pvc
  namespace: fase4-tech-challenge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
