apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config
  namespace: fase4-tech-challenge
data:
  # RabbitMQ Config
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_QUEUE_NAME: contact-queue
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest

  # Client API
  PERSISTENCE_API_URL: "http://persistence-api-service:8080"

  