apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: fase4-tech-challenge
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'persistence-api'
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets: ['persistence-api-service:8080']

      - job_name: 'client-api'
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets: ['client-api-service:8082']