apiVersion: v1
kind: Service
metadata:
  name: persistence-api-service
  namespace: fase4-tech-challenge
spec:
  selector:
    app: persistence-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort