apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: fase4-tech-challenge
spec:
  selector:
    app: prometheus
  ports:
    - name: web
      port: 9090
      targetPort: 9090
      nodePort: 30090
  type: NodePort